package com.eulerity.task_manager.service;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.verifyNoInteractions;
import static org.mockito.Mockito.when;

import java.time.Clock;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;

import org.junit.jupiter.api.Test;

import com.eulerity.task_manager.dto.TaskSuggestRequest;
import com.eulerity.task_manager.dto.TaskSuggestResponse;
import com.eulerity.task_manager.model.Priority;
import com.eulerity.task_manager.model.Status;

class TaskSuggestionServiceImplTest {

    @Test
    void suggest_usesFallbackWhenApiKeyIsMissing() {
        TaskSuggestionClient client = mock(TaskSuggestionClient.class);
        TaskSuggestionFallbackParser fallbackParser = new TaskSuggestionFallbackParser(
                Clock.fixed(Instant.parse("2026-04-27T10:00:00Z"), ZoneId.of("America/New_York"))
        );
        TaskSuggestionService service = new TaskSuggestionServiceImpl(client, fallbackParser, "");

        TaskSuggestResponse response = service.suggest(new TaskSuggestRequest(
                "urgent interview prep for tomorrow"
        ));

        assertThat(response.title()).isEqualTo("Urgent Interview Prep For");
        assertThat(response.description()).isEqualTo("Suggested from prompt: urgent interview prep for tomorrow");
        assertThat(response.dueDate()).isEqualTo(LocalDate.of(2026, 4, 28));
        assertThat(response.priority()).isEqualTo(Priority.HIGH);
        assertThat(response.status()).isEqualTo(Status.TODO);
        verifyNoInteractions(client);
    }

    @Test
    void suggest_delegatesToClientWhenApiKeyIsPresent() {
        TaskSuggestionClient client = mock(TaskSuggestionClient.class);
        TaskSuggestionFallbackParser fallbackParser = new TaskSuggestionFallbackParser(
                Clock.fixed(Instant.parse("2026-04-27T10:00:00Z"), ZoneId.of("America/New_York"))
        );
        TaskSuggestionService service = new TaskSuggestionServiceImpl(client, fallbackParser, "test-key");
        TaskSuggestRequest request = new TaskSuggestRequest("plan my week");
        TaskSuggestResponse clientResponse = new TaskSuggestResponse(
                "Client Result",
                "Generated by dedicated AI client",
                LocalDate.of(2026, 5, 4),
                Priority.MEDIUM,
                Status.TODO
        );
        when(client.suggest(request)).thenReturn(clientResponse);

        TaskSuggestResponse response = service.suggest(request);

        assertThat(response).isEqualTo(clientResponse);
        verify(client).suggest(request);
    }
}
